name       : python-diff-match-patch
version    : 20200713
release    : 1
source     :
    - https://github.com/diff-match-patch-python/diff-match-patch/archive/v20200713.tar.gz : e82dfc36b44abc8e6142ecd81b09325347c913ab1dfbcbb06fca89f4147cee17
homepage   : https://github.com/diff-match-patch-python/diff-match-patch
license    : Apache-2.0
component  : programming.python
summary    : Diff Match Patch is a high-performance library in multiple languages that manipulates plain text
description: |
    Diff Match Patch is a high-performance library in multiple languages that manipulates plain text. 
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
