name       : python-diff-match-patch
version    : '20230430'
release    : 4
source     :
    - https://github.com/diff-match-patch-python/diff-match-patch/archive/refs/tags/v20230430.tar.gz : 4fe7f91f735818564fe2b847cbd008be3309f41e7821d5e1cee3693aab7e32c1
homepage   : https://github.com/diff-match-patch-python/diff-match-patch
license    : Apache-2.0
component  : programming.python
summary    : Diff Match Patch is a high-performance library in multiple languages that manipulates plain text
description: |
    Diff Match Patch is a high-performance library in multiple languages that manipulates plain text. 
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
    - python-pytest    # check
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
